//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/whm-marketplace/main.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/whm-marketplace/main-ja.js
// Module:    /templates/whm-marketplace/main-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Activation Date":"アクティベーション日","Active":"アクティブ","Add Available Extensions":"利用可能な拡張機能を追加","Add Extensions":"拡張機能を追加","Back to Manage Your Extensions":"拡張機能の管理に戻る","Collapsed":"折りたたみ済み","Expanded":"展開済み","Expiration Date":"有効期限","Extension":"拡張機能","Featured":"注目","Free":"空き","Free[comment,without cost]":"無料[comment,without cost]","Inactive":"非アクティブ","Install":"インストール","Installation successful.":"インストールが成功しました。","License Status":"ライセンスステータス","Loading licenses for this [output,abbr,IP,Internet Protocol] address.":"この[output,abbr,IP,インターネットプロトコル] アドレスでライセンスをロード中です。","Manage":"管理","Manage Your Extensions":"拡張機能を管理","Manage the “[_1]” extension.":"「[_1]」拡張子を管理します。","N/A":"なし","Paid[comment,not free of charge]":"有料[comment,not free of charge]","Product":"製品","Purchase":"購入","There are no new extensions for you to purchase or install. Check back later as we continue to grow our catalog.":"購入またはインストールできる、新しいプラグインはありません。今後もカタログを増やしていきますので、後日またご覧ください。","There are not any licenses associated with this [output,abbr,IP,Internet Protocol] address.":"この[output,abbr,IP,インターネットプロトコル]アドレスに関連するライセンスはありません。","There was a problem with the install. Refresh the page and try again.":"インストールに問題がありました。ページを更新し、もう一度やり直してください。","This interface enables you to manage licenses on your server as well as install products with active licenses.":"このインターフェースでは、サーバ上のライセンスを管理し、アクティブなライセンスの製品をインストールすることができます。","[datetime,_1]":"[datetime,_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
