//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/whm-marketplace/main.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/whm-marketplace/main-pt_br.js
// Module:    /templates/whm-marketplace/main-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Activation Date":"Data da Ativação","Active":"Ativo","Add Available Extensions":"Adicionar Extensões Disponíveis","Add Extensions":"Adicionar Extensões","Back to Manage Your Extensions":"Voltar para Gerenciar suas Extensões","Collapsed":"Reduzido","Expanded":"Expandido","Expiration Date":"Data de Validade","Extension":"Extensão","Featured":"Em destaque","Free":"Grátis","Free[comment,without cost]":"Grátis[comment,without cost]","Inactive":"Inativo","Install":"Instalar","Installation successful.":"Instalação bem-sucedida.","License Status":"Status da Licença","Loading licenses for this [output,abbr,IP,Internet Protocol] address.":"Carregando licenças para esse endereço [output,abbr,IP,IP].","Manage":"Gerenciar","Manage Your Extensions":"Gerenciar Suas Extensões","Manage the “[_1]” extension.":"Gerenciar a extensão “[_1]”.","N/A":"N/A","Paid[comment,not free of charge]":"Pago[comment,not free of charge]","Product":"Produto","Purchase":"Comprar","There are no new extensions for you to purchase or install. Check back later as we continue to grow our catalog.":"Não há novas extensões para você comprar ou instalar. Volte mais tarde enquanto continuamos a aumentar nosso catálogo.","There are not any licenses associated with this [output,abbr,IP,Internet Protocol] address.":"Não há licenças associadas a esse endereço [output,abbr,IP,IP].","There was a problem with the install. Refresh the page and try again.":"Houve um problema com a instalação. Atualize a página e tente novamente.","This interface enables you to manage licenses on your server as well as install products with active licenses.":"Essa interface permite gerenciar licenças em seu servidor, bem como instalar produtos com licenças ativas.","[datetime,_1]":"[datetime,_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
