//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/whm-marketplace/main.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/whm-marketplace/main-fil.js
// Module:    /templates/whm-marketplace/main-fil
// Locale:    fil
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Activation Date":"Activation Date","Active":"Active","Add Available Extensions":"Add Available Extensions","Add Extensions":"Add Extensions","Back to Manage Your Extensions":"Back to Manage Your Extensions","Collapsed":"Collapsed","Expanded":"Expanded","Expiration Date":"Expiration Date","Extension":"Extension","Featured":"Featured","Free":"Free","Free[comment,without cost]":"Free[comment,without cost]","Inactive":"Inactive","Install":"I-install","Installation successful.":"Installation successful.","License Status":"License Status","Loading licenses for this [output,abbr,IP,Internet Protocol] address.":"Loading licenses for this [output,abbr,IP,Internet Protocol] address.","Manage":"Pamahalaan","Manage Your Extensions":"Manage Your Extensions","Manage the “[_1]” extension.":"Manage the “[_1]” extension.","N/A":"N/A","Paid[comment,not free of charge]":"Paid[comment,not free of charge]","Product":"Product","Purchase":"Purchase","There are no new extensions for you to purchase or install. Check back later as we continue to grow our catalog.":"There are no new extensions for you to purchase or install. Check back later as we continue to grow our catalog.","There are not any licenses associated with this [output,abbr,IP,Internet Protocol] address.":"There are not any licenses associated with this [output,abbr,IP,Internet Protocol] address.","There was a problem with the install. Refresh the page and try again.":"There was a problem with the install. Refresh the page and try again.","This interface enables you to manage licenses on your server as well as install products with active licenses.":"This interface enables you to manage licenses on your server as well as install products with active licenses.","[datetime,_1]":"[datetime,_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
