//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/whm-marketplace/main.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/whm-marketplace/main-es_es.js
// Module:    /templates/whm-marketplace/main-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Activation Date":"Fecha de activación","Active":"Activo","Add Available Extensions":"Añadir extensiones disponibles","Add Extensions":"Añadir extensiones","Back to Manage Your Extensions":"Volver a administrar sus extensiones","Collapsed":"Contraído","Expanded":"Ampliado","Expiration Date":"Fecha de expiración","Extension":"Extensión","Featured":"Destacado","Free":"Gratis","Free[comment,without cost]":"Gratuito[comment,without cost]","Inactive":"Inactiva","Install":"Instalar","Installation successful.":"Instalación completada correctamente.","License Status":"Estado de la licencia","Loading licenses for this [output,abbr,IP,Internet Protocol] address.":"Cargando licencias para esta dirección [output,abbr,IP,IP].","Manage":"Administrar","Manage Your Extensions":"Administrar sus extensiones","Manage the “[_1]” extension.":"Administre la extensión “[_1]”.","N/A":"N/D","Paid[comment,not free of charge]":"De pago[comment,not free of charge]","Product":"Producto","Purchase":"Comprar","There are no new extensions for you to purchase or install. Check back later as we continue to grow our catalog.":"No existe ninguna extensión nueva que pueda instalar o comparar. Compruébelo más tarde, puesto que nuestro catálogo de extensiones va ampliándose de forma continuada.","There are not any licenses associated with this [output,abbr,IP,Internet Protocol] address.":"No existe ninguna licencia asociada con esta dirección [output,abbr,IP,IP].","There was a problem with the install. Refresh the page and try again.":"Se produjo un problema con la instalación. Actualice la página e inténtelo de nuevo.","This interface enables you to manage licenses on your server as well as install products with active licenses.":"Esta interfaz le permite administrar licencias de su servidor, así como instalar productos con licencias activas.","[datetime,_1]":"[datetime,_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
