//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/whm-marketplace/main.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/whm-marketplace/main-id.js
// Module:    /templates/whm-marketplace/main-id
// Locale:    id
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Activation Date":"Tanggal Aktivasi","Active":"Aktif","Add Available Extensions":"Tambah Ekstensi Tersedia","Add Extensions":"Tambah Ekstensi","Back to Manage Your Extensions":"Kembali ke Kelola Ekstensi Anda","Collapsed":"Diperkecil","Expanded":"Diperluas","Expiration Date":"Tanggal Kedaluwarsa","Extension":"Ekstensi","Featured":"Disorot","Free":"Gratis","Free[comment,without cost]":"Gratis[comment,without cost]","Inactive":"Tidak aktif","Install":"Instal","Installation successful.":"Penginstalan berhasil.","License Status":"Status Lisensi","Loading licenses for this [output,abbr,IP,Internet Protocol] address.":"Memuat lisensi untuk alamat [output,abbr,IP,Internet Protocol].","Manage":"Kelola","Manage Your Extensions":"Kelola Ekstensi Anda","Manage the “[_1]” extension.":"Kelola ekstensi “[_1]”.","N/A":"Tidak Ada","Paid[comment,not free of charge]":"Berbayar[comment,not free of charge]","Product":"Produk","Purchase":"Pembelian","There are no new extensions for you to purchase or install. Check back later as we continue to grow our catalog.":"Tidak ada ekstensi baru yang dapat Anda beli atau instal. Periksa kembali nanti karena kami terus mengembangkan katalog kami.","There are not any licenses associated with this [output,abbr,IP,Internet Protocol] address.":"Tidak ada lisensi yang berkaitan dengan alamat [output,abbr,IP,Protokol Internet] ini.","There was a problem with the install. Refresh the page and try again.":"Ada masalah dengan instalasi. Muat ulang halaman dan coba lagi.","This interface enables you to manage licenses on your server as well as install products with active licenses.":"Antarmuka ini memungkinkan Anda mengelola lisensi di server Anda serta menginstal produk dengan lisensi yang aktif.","[datetime,_1]":"[datetime,_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
