//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/main.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/main-id.js
// Module:    /templates/account-enhancements/main-id
// Locale:    id
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Item Identifier":"Pengidentifikasi Item","Loading …":"Memuat …","Name":"Nama","No results available.":"Hasil tidak tersedia.","No results match your query.":"Tidak ada hasil yang cocok dengan kueri Anda.","Refresh":"Segarkan","Table Settings":"Pengaturan Tabel","You can use this interface to view and manage your server‘s account enhancements.":"Anda dapat menggunakan antarmuka ini untuk melihat dan mengelola peningkatan akun server Anda."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
