//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/main.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/main-zh_tw.js
// Module:    /templates/account-enhancements/main-zh_tw
// Locale:    zh_tw
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Item Identifier":"Item Identifier","Loading …":"正在載入…","Name":"名稱","No results available.":"No results available.","No results match your query.":"沒有符合查詢的結果。","Refresh":"重新整理","Table Settings":"Table Settings","You can use this interface to view and manage your server‘s account enhancements.":"You can use this interface to view and manage your server‘s account enhancements."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
