//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/main.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/main-pt_br.js
// Module:    /templates/account-enhancements/main-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Item Identifier":"Identificador de item","Loading …":"Carregando …","Name":"Nome","No results available.":"Nenhum resultado disponível.","No results match your query.":"Nenhum resultado corresponde à sua consulta.","Refresh":"Atualizar","Table Settings":"Configurações da tabela","You can use this interface to view and manage your server‘s account enhancements.":"Você pode usar esta interface para visualizar e gerenciar os aprimoramentos da conta do seu servidor."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
