//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/main.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/main-es_es.js
// Module:    /templates/account-enhancements/main-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Item Identifier":"Identificador de elemento","Loading …":"Cargando …","Name":"Nombre","No results available.":"Ningún resultado disponible.","No results match your query.":"No hay resultados que coincidan con su consulta.","Refresh":"Actualizar","Table Settings":"Configuración de la tabla","You can use this interface to view and manage your server‘s account enhancements.":"Puede usar esta interfaz para ver y gestionar las mejoras de cuenta de su servidor."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
