//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/vendor-de.js
// Module:    /templates/account-enhancements/vendor-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"All":"Alle","Clear Input":"Eingabe löschen","Close":"Schließen","Entries Per Page":"Einträge pro Seite","Error:":"Fehler:","Information:":"Informationen:","More":"Mehr","Search":"Suchen","Show [quant,_1,entry per page,entries per page]":"Show [quant,_1,entry per page,entries per page]","Show all entries":"Alle Einträge anzeigen","Success:":"Erfolgreich:","Warning:":"Warnung:","[_1] - [_2] of [_3]":"[_1] - [_2] of [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
