//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/vendor-es_es.js
// Module:    /templates/account-enhancements/vendor-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"All":"Todo","Clear Input":"Borrar entrada","Close":"Cerrar","Entries Per Page":"Entradas por página","Error:":"Error:","Information:":"Información:","More":"Más","Search":"Buscar","Show [quant,_1,entry per page,entries per page]":"Mostrar [quant,_1,entrada por página,entradas por página]","Show all entries":"Mostrar todas las entradas","Success:":"Correcto:","Warning:":"Advertencia:","[_1] - [_2] of [_3]":"[_1] - [_2] de [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
