//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/vendor-el.js
// Module:    /templates/account-enhancements/vendor-el
// Locale:    el
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"All":"Όλα","Clear Input":"Clear Input","Close":"Κλείσιμο","Entries Per Page":"Entries Per Page","Error:":"Σφάλμα:","Information:":"Πληροφορίες:","More":"Περισσότερα","Search":"Αναζήτηση","Show [quant,_1,entry per page,entries per page]":"Show [quant,_1,entry per page,entries per page]","Show all entries":"Show all entries","Success:":"Επιτυχία:","Warning:":"Προειδοποίηση:","[_1] - [_2] of [_3]":"[_1] - [_2] of [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
