//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/account-enhancements/vendor-th.js
// Module:    /templates/account-enhancements/vendor-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"All":"ทั้งหมด","Clear Input":"Clear Input","Close":"ปิด","Entries Per Page":"Entries Per Page","Error:":"ข้อผิดพลาด:","Information:":"ข้อมูล:","More":"เพิ่มเติม","Search":"ค้นหา","Show [quant,_1,entry per page,entries per page]":"Show [quant,_1,entry per page,entries per page]","Show all entries":"Show all entries","Success:":"สำเร็จ:","Warning:":"คำเตือน:","[_1] - [_2] of [_3]":"[_1] - [_2] of [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
