//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/manage-calendar-access/vendor.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/manage-calendar-access/vendor-ko.js
// Module:    /jupiter/manage-calendar-access/vendor-ko
// Locale:    ko
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Close":"닫기","Error:":"오류:","Information:":"정보:","Loading …":"로드하는 중 …","More":"기타","Success:":"성공:","Warning:":"경고:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
