//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/manage-calendar-access/vendor.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/manage-calendar-access/vendor-it.js
// Module:    /jupiter/manage-calendar-access/vendor-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Close":"Chiudi","Error:":"Errore:","Information:":"Informazioni:","Loading …":"Caricamento in corso…","More":"Altro","Success:":"Operazione completata:","Warning:":"Avvertenza:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
