//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/manage-calendar-access/vendor.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/manage-calendar-access/vendor-zh_tw.js
// Module:    /jupiter/manage-calendar-access/vendor-zh_tw
// Locale:    zh_tw
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Close":"關閉","Error:":"錯誤:","Information:":"資訊:","Loading …":"正在載入…","More":"其他","Success:":"成功:","Warning:":"警告:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
