//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/nginx-manager/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/nginx-manager/vendor-ru.js
// Module:    /templates/nginx-manager/vendor-ru
// Locale:    ru
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"All":"Все","Clear Input":"Очистить ввод","Close":"Закрыть","Entries Per Page":"Записей на странице","Error:":"Ошибка:","Information:":"Информация:","More":"Еще","Search":"Поиск","Show [quant,_1,entry per page,entries per page]":"Show [quant,_1,entry per page,entries per page]","Show all entries":"Показать все записи","Success:":"Успешно:","Warning:":"Предупреждение:","[_1] - [_2] of [_3]":"[_1] - [_2] of [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
