//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/nginx-manager/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/nginx-manager/vendor-uk.js
// Module:    /templates/nginx-manager/vendor-uk
// Locale:    uk
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"All":"Усі","Clear Input":"Clear Input","Close":"Закрити","Entries Per Page":"Entries Per Page","Error:":"Помилка.","Information:":"Інформація.","More":"Більше","Search":"Пошук","Show [quant,_1,entry per page,entries per page]":"Show [quant,_1,entry per page,entries per page]","Show all entries":"Show all entries","Success:":"Вітаємо!","Warning:":"Попередження.","[_1] - [_2] of [_3]":"[_1] - [_2] of [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
