//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/nginx-manager/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/nginx-manager/vendor-id.js
// Module:    /templates/nginx-manager/vendor-id
// Locale:    id
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"All":"Semua","Clear Input":"Bersihkan Input","Close":"Tutup","Entries Per Page":"Entri Per Halaman","Error:":"Kesalahan:","Information:":"Informasi:","More":"Lainnya","Search":"Cari","Show [quant,_1,entry per page,entries per page]":"Tampilkan [quant,_1, entri per halaman, entri per halaman]","Show all entries":"Tampilkan semua entri","Success:":"Berhasil:","Warning:":"Peringatan:","[_1] - [_2] of [_3]":"[_1] - [_2] dari [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
