#!/usr/local/cpanel/3rdparty/bin/perl

#                                      Copyright 2024 WebPros International, LLC
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited.

package libexec::on_boot::populate_system_needs_reboot;

use cPstrict;

use Cpanel::ServerTasks ();

exit( script(@ARGV) ) unless caller();

sub script {
    Cpanel::ServerTasks::schedule_task( ['SystemTasks'], 5, "recache_system_reboot_data" );
    return 0;
}

1;
