//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/ssl-tls-configuration/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/ssl-tls-configuration/vendor-id.js
// Module:    /templates/ssl-tls-configuration/vendor-id
// Locale:    id
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Close":"Tutup","Collapse":"Perkecil","Error:":"Kesalahan:","Expand":"Perluas","Information:":"Informasi:","Loading …":"Memuat …","More":"Lainnya","Success:":"Berhasil:","Warning:":"Peringatan:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
