//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/ssl-tls-configuration/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/ssl-tls-configuration/vendor-uk.js
// Module:    /templates/ssl-tls-configuration/vendor-uk
// Locale:    uk
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Close":"Закрити","Collapse":"Collapse","Error:":"Помилка.","Expand":"Expand","Information:":"Інформація.","Loading …":"Завантаження…","More":"Більше","Success:":"Вітаємо!","Warning:":"Попередження."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
