//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/ssl-tls-configuration/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/ssl-tls-configuration/vendor-nb.js
// Module:    /templates/ssl-tls-configuration/vendor-nb
// Locale:    nb
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Close":"Lukk","Collapse":"Collapse","Error:":"Feil:","Expand":"Expand","Information:":"Informasjon:","Loading …":"Laster inn …","More":"Flere","Success:":"Vellykket:","Warning:":"Advarsel:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
