//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/multiphp-manager-ng7/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/multiphp-manager-ng7/vendor-zh.js
// Module:    /templates/multiphp-manager-ng7/vendor-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Clear Input":"Clear Input","Close":"关闭","Collapse":"折叠","Error:":"错误:","Expand":"展开","Information:":"信息:","Loading …":"正在加载…","More":"更多信息","Search":"搜索","Success:":"成功:","Warning:":"警告:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
