//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/multiphp-manager-ng7/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/multiphp-manager-ng7/vendor-pl.js
// Module:    /templates/multiphp-manager-ng7/vendor-pl
// Locale:    pl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Clear Input":"Clear Input","Close":"Zamknij","Collapse":"Zwiń","Error:":"Błąd:","Expand":"Rozwiń","Information:":"Informacje:","Loading …":"Ładowanie…","More":"Więcej","Search":"Wyszukaj","Success:":"Powodzenie:","Warning:":"Ostrzeżenie:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
