//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/whostmgr/docroot/templates/multiphp-manager-ng7/vendor.js
// Generated: /usr/local/cpanel/whostmgr/docroot/templates/multiphp-manager-ng7/vendor-cs.js
// Module:    /templates/multiphp-manager-ng7/vendor-cs
// Locale:    cs
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Clear Input":"Clear Input","Close":"Zavřít","Collapse":"Collapse","Error:":"Chyba:","Expand":"Expand","Information:":"Informace:","Loading …":"Načítání…","More":"Další","Search":"Hledat","Success:":"Úspěch:","Warning:":"Upozornění:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
