//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/jupiter/clam-av/vendor.js
// Generated: /usr/local/cpanel/base/frontend/jupiter/clam-av/vendor-sv.js
// Module:    /jupiter/clam-av/vendor-sv
// Locale:    sv
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Close":"Stäng","Error:":"Fel:","Information:":"Information:","Loading …":"Läser in …","More":"Mer","Success:":"Klart:","Warning:":"Varning!"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
